/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InstancesIdRouteImport } from './routes/instances.$id'
import { Route as ApiEventsRouteImport } from './routes/api/events'
import { Route as InstancesIdIndexRouteImport } from './routes/instances.$id.index'
import { Route as InstancesIdWorkersRouteImport } from './routes/instances.$id.workers'
import { Route as ApiTrpcSplatRouteImport } from './routes/api.trpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as InstancesIdQueuesQueueRouteImport } from './routes/instances.$id.queues.$queue'
import { Route as InstancesIdQueuesQueueJobsJobIdRouteImport } from './routes/instances.$id.queues.$queue.jobs.$jobId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstancesIdRoute = InstancesIdRouteImport.update({
  id: '/instances/$id',
  path: '/instances/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsRoute = ApiEventsRouteImport.update({
  id: '/api/events',
  path: '/api/events',
  getParentRoute: () => rootRouteImport,
} as any)
const InstancesIdIndexRoute = InstancesIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InstancesIdRoute,
} as any)
const InstancesIdWorkersRoute = InstancesIdWorkersRouteImport.update({
  id: '/workers',
  path: '/workers',
  getParentRoute: () => InstancesIdRoute,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const InstancesIdQueuesQueueRoute = InstancesIdQueuesQueueRouteImport.update({
  id: '/queues/$queue',
  path: '/queues/$queue',
  getParentRoute: () => InstancesIdRoute,
} as any)
const InstancesIdQueuesQueueJobsJobIdRoute =
  InstancesIdQueuesQueueJobsJobIdRouteImport.update({
    id: '/jobs/$jobId',
    path: '/jobs/$jobId',
    getParentRoute: () => InstancesIdQueuesQueueRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/events': typeof ApiEventsRoute
  '/instances/$id': typeof InstancesIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/instances/$id/workers': typeof InstancesIdWorkersRoute
  '/instances/$id/': typeof InstancesIdIndexRoute
  '/instances/$id/queues/$queue': typeof InstancesIdQueuesQueueRouteWithChildren
  '/instances/$id/queues/$queue/jobs/$jobId': typeof InstancesIdQueuesQueueJobsJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/events': typeof ApiEventsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/instances/$id/workers': typeof InstancesIdWorkersRoute
  '/instances/$id': typeof InstancesIdIndexRoute
  '/instances/$id/queues/$queue': typeof InstancesIdQueuesQueueRouteWithChildren
  '/instances/$id/queues/$queue/jobs/$jobId': typeof InstancesIdQueuesQueueJobsJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/events': typeof ApiEventsRoute
  '/instances/$id': typeof InstancesIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/instances/$id/workers': typeof InstancesIdWorkersRoute
  '/instances/$id/': typeof InstancesIdIndexRoute
  '/instances/$id/queues/$queue': typeof InstancesIdQueuesQueueRouteWithChildren
  '/instances/$id/queues/$queue/jobs/$jobId': typeof InstancesIdQueuesQueueJobsJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/events'
    | '/instances/$id'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/instances/$id/workers'
    | '/instances/$id/'
    | '/instances/$id/queues/$queue'
    | '/instances/$id/queues/$queue/jobs/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/events'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/instances/$id/workers'
    | '/instances/$id'
    | '/instances/$id/queues/$queue'
    | '/instances/$id/queues/$queue/jobs/$jobId'
  id:
    | '__root__'
    | '/'
    | '/api/events'
    | '/instances/$id'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/instances/$id/workers'
    | '/instances/$id/'
    | '/instances/$id/queues/$queue'
    | '/instances/$id/queues/$queue/jobs/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiEventsRoute: typeof ApiEventsRoute
  InstancesIdRoute: typeof InstancesIdRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instances/$id': {
      id: '/instances/$id'
      path: '/instances/$id'
      fullPath: '/instances/$id'
      preLoaderRoute: typeof InstancesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events': {
      id: '/api/events'
      path: '/api/events'
      fullPath: '/api/events'
      preLoaderRoute: typeof ApiEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instances/$id/': {
      id: '/instances/$id/'
      path: '/'
      fullPath: '/instances/$id/'
      preLoaderRoute: typeof InstancesIdIndexRouteImport
      parentRoute: typeof InstancesIdRoute
    }
    '/instances/$id/workers': {
      id: '/instances/$id/workers'
      path: '/workers'
      fullPath: '/instances/$id/workers'
      preLoaderRoute: typeof InstancesIdWorkersRouteImport
      parentRoute: typeof InstancesIdRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instances/$id/queues/$queue': {
      id: '/instances/$id/queues/$queue'
      path: '/queues/$queue'
      fullPath: '/instances/$id/queues/$queue'
      preLoaderRoute: typeof InstancesIdQueuesQueueRouteImport
      parentRoute: typeof InstancesIdRoute
    }
    '/instances/$id/queues/$queue/jobs/$jobId': {
      id: '/instances/$id/queues/$queue/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/instances/$id/queues/$queue/jobs/$jobId'
      preLoaderRoute: typeof InstancesIdQueuesQueueJobsJobIdRouteImport
      parentRoute: typeof InstancesIdQueuesQueueRoute
    }
  }
}

interface InstancesIdQueuesQueueRouteChildren {
  InstancesIdQueuesQueueJobsJobIdRoute: typeof InstancesIdQueuesQueueJobsJobIdRoute
}

const InstancesIdQueuesQueueRouteChildren: InstancesIdQueuesQueueRouteChildren =
  {
    InstancesIdQueuesQueueJobsJobIdRoute: InstancesIdQueuesQueueJobsJobIdRoute,
  }

const InstancesIdQueuesQueueRouteWithChildren =
  InstancesIdQueuesQueueRoute._addFileChildren(
    InstancesIdQueuesQueueRouteChildren,
  )

interface InstancesIdRouteChildren {
  InstancesIdWorkersRoute: typeof InstancesIdWorkersRoute
  InstancesIdIndexRoute: typeof InstancesIdIndexRoute
  InstancesIdQueuesQueueRoute: typeof InstancesIdQueuesQueueRouteWithChildren
}

const InstancesIdRouteChildren: InstancesIdRouteChildren = {
  InstancesIdWorkersRoute: InstancesIdWorkersRoute,
  InstancesIdIndexRoute: InstancesIdIndexRoute,
  InstancesIdQueuesQueueRoute: InstancesIdQueuesQueueRouteWithChildren,
}

const InstancesIdRouteWithChildren = InstancesIdRoute._addFileChildren(
  InstancesIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiEventsRoute: ApiEventsRoute,
  InstancesIdRoute: InstancesIdRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
